name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true 

jobs:
  Build:
    runs-on:  ubuntu-latest
    steps:
      - run: |
          echo "job was triggered by event: ${{ github.event_name }}"
          echo "name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }} ."

      - uses: actions/checkout@v3.0.2

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
          
      - name: Generate SBOM
        # You may pin to the exact commit or the version.
        # uses: advanced-security/generate-sbom-action@ded26bf491ccc4b8c43f6c7ac2e1ff35e960c0d0
        uses: advanced-security/generate-sbom-action@v1
        with:
          # GitHub token with permissions to read SBOM
          token:  ${{ github.token }}
